{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:{{ include "vad-kostar-bostaden.serviceAccountName" . }}-restricted
roleRef:
  kind: ClusterRole
  name: psp:restricted
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "vad-kostar-bostaden.serviceAccountName" . }}
    namespace: {{ .Release.namespace }}
{{- end }}
