name: "prod: Build and deploy"

on:
  workflow_dispatch:

jobs:
  build:
    uses: jonashartwig/vad-kostar-bostaden/.github/workflows/workflow.yaml@master
    secrets:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    with:
      appName: vad-kostar-bostaden
